[package]
name = "spcp-mini"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0"
spc-spcp = { path = "../spc-spcp" }
snes-apu-spcp = { path = "../snes-apu-spcp" }
rodio = "0.18.1"
slint = { version = "1.6.0", features = ["raw-window-handle-06"] }
i-slint-backend-winit = "=1.6.0"
native-dialog = "0.7.0"
souvlaki = "0.7.3"

[build-dependencies]
slint-build = "1.6.0"
