[package]
name = "spcp-mini"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0"
spc-spcp = { path = "../spc-spcp" }
snes-apu-spcp = { path = "../snes-apu-spcp" }
rodio = "0.18.1"
hound = "3.3.1"
slint = "1.6.0"
native-dialog = "0.7.0"

[build-dependencies]
slint-build = "1.6.0"
